CREATE TABLE IF NOT EXISTS public.admins (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamp(6) NOT NULL,
	mobile_phone varchar(11) NOT NULL,
	"name" varchar(100) NOT NULL,
	password_hash varchar(255) NOT NULL,
	"role" varchar(30) NOT NULL,
	username varchar(100) NOT NULL,
	CONSTRAINT admins_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.events (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	admin_id int8 NOT NULL,
	created_at timestamp(6) NOT NULL,
	"date" timestamp(6) NOT NULL,
	description text NOT NULL,
	"name" varchar(100) NOT NULL,
	visible bool NOT NULL,
	CONSTRAINT events_pkey PRIMARY KEY (id),
	CONSTRAINT uniq_name UNIQUE (name),
	CONSTRAINT fk_event_admin FOREIGN KEY (admin_id) REFERENCES admins (id) on delete cascade
);

CREATE TABLE IF NOT EXISTS public.posters (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	event_id int8 NOT NULL,
	image_data bytea NOT NULL,
	CONSTRAINT posters_pkey PRIMARY KEY (id),
	CONSTRAINT fk_posters_events FOREIGN KEY (event_id) REFERENCES events (id) on delete cascade
);

CREATE TABLE IF NOT EXISTS public.sectors (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	color varchar(10) NOT NULL,
	event_id int8 NOT NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT sectors_pkey PRIMARY KEY (id),
	CONSTRAINT fk_sector_event FOREIGN KEY (event_id) REFERENCES events (id) on delete cascade
);

CREATE TABLE IF NOT EXISTS public.seats (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	reserved bool NOT NULL,
	row_and_seat_number varchar(10) NOT NULL,
	sector_id int8 NOT NULL,
	CONSTRAINT seats_pkey PRIMARY KEY (id),
	CONSTRAINT fk_seat_sector FOREIGN KEY (sector_id) REFERENCES sectors (id) on delete cascade
);

CREATE TABLE IF NOT EXISTS public.visitors (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	fathername varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	surname varchar(100) NOT NULL,
	email varchar(100) NOT NULL,
	CONSTRAINT visitors_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tickets (
	uuid uuid NOT NULL,
	created timestamp(6) NULL,
	event_id int8 NOT NULL,
	seat_id int8 NOT NULL,
	sector_id int8 NOT NULL,
	ticket_status varchar(50) NULL,
	visitor_id int8 NOT NULL,
	CONSTRAINT tickets_pkey PRIMARY KEY (uuid),
	CONSTRAINT tickets_ticket_status_check CHECK (((ticket_status)::text = ANY ((ARRAY['CREATED'::character varying, 'CANCELED'::character varying, 'USED'::character varying, 'BANNED'::character varying])::text[]))),
    CONSTRAINT fk_ticket_event FOREIGN KEY (event_id) REFERENCES events (id) on delete cascade,
    CONSTRAINT fk_ticket_seat FOREIGN KEY (seat_id) REFERENCES seats (id) on delete cascade,
    CONSTRAINT fk_ticket_sector FOREIGN KEY (sector_id) REFERENCES sectors (id) on delete cascade,
    CONSTRAINT fk_ticket_visitor FOREIGN KEY (visitor_id) REFERENCES visitors (id) on delete cascade,
    CONSTRAINT unique_event_seat_status UNIQUE (event_id, seat_id, ticket_status)

);
